### PR TITLE
added the volume modal display in the gamesplay

### LINKED ISSUE #28: Add volume control for background music
Add volume control for background music on the mute and unmute buttons across each screen

CleanShot 2024-06-11 at 13 44 25@2x

CleanShot 2024-06-11 at 13 44 50@2x

### PR DESCRIPTION
**Pull request by Dprof-in-tech**
image
I'm done with adding the volume controls across the gameplay screen.

closes #28

### CODE REVIEW

**Comment by supreme2580** [comment]
Hi @Dprof-in-tech I am currently reviewing your PR and I noticed a few things

This is how the figma design looks

image

This is how it looks from your code

image

A few things are off, namely

- The mute/unmute button is tiny and too far away from Playing - Storms in Africa
- The chevron arrow indicating whether the volume change popup is open or not is not point up/down based on the state of the popup (open/close)
- The entire field should be clickable not just the chevron arrow
- The cursor type for the entire field should be pointer not just for the chevron arrow button
- The volume track pad cursor type should not be pointer it should be grab
- The thumb of the track pad color should be #FCE3AA and the track should be #E48D32
- The volume icon is also tiny and incorrect
- The color of the volume icon should be #FCE3AA 
- The control buttons should have cursor type pointer

Also in the code, this 

```
< style> {
    `

    /* Custom styles for the input thumb */
    input[type="range"]::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 0;
        /* width of the thumb */
        height: 0;
        /* height of the thumb */
        background: transparent;
        /* thumb background color */
        cursor: pointer;
    }

    input[type="range"]::-moz-range-thumb {
        width: 0;
        height: 0;
        background: transparent;
        border: none;
        cursor: pointer;
    }

    `
}

< /style>
```

This isn't acceptable in the gameplay.tsx do this in the index.css file instead

**Comment by Dprof-in-tech** [comment]
> Hi @Dprof-in-tech I am currently reviewing your PR and I noticed a few things
> 
> 
> 
> This is how the figma design looks
> 
> 
> 
> image
> 
> 
> 
> This is how it looks from your code
> 
> 
> 
> image
> 
> 
> 
> A few things are off, namely
> 
> 
> 
> - The mute/unmute button is tiny and too far away from Playing - Storms in Africa
> 
> - The chevron arrow indicating whether the volume change popup is open or not is not point up/down based on the state of the popup (open/close)
> 
> - The entire field should be clickable not just the chevron arrow
> 
> - The cursor type for the entire field should be pointer not just for the chevron arrow button
> 
> - The volume track pad cursor type should not be pointer it should be grab
> 
> - The thumb of the track pad color should be #FCE3AA and the track should be #E48D32
> 
> - The volume icon is also tiny and incorrect
> 
> - The color of the volume icon should be #FCE3AA 
> 
> - The control buttons should have cursor type pointer
> 
> - The background color should be transparent but blurred
> 
> 
> 
> Also in the code, this 
> 
> 
> 
> ```
> 
> < style> {
> 
>     `
> 
> 
> 
>     /* Custom styles for the input thumb */
> 
>     input[type="range"]::-webkit-slider-thumb {
> 
>         -webkit-appearance: none;
> 
>         appearance: none;
> 
>         width: 0;
> 
>         /* width of the thumb */
> 
>         height: 0;
> 
>         /* height of the thumb */
> 
>         background: transparent;
> 
>         /* thumb background color */
> 
>         cursor: pointer;
> 
>     }
> 
> 
> 
>     input[type="range"]::-moz-range-thumb {
> 
>         width: 0;
> 
>         height: 0;
> 
>         background: transparent;
> 
>         border: none;
> 
>         cursor: pointer;
> 
>     }
> 
> 
> 
>     `
> 
> }
> 
> 
> 
> < /style>
> 
> ```
> 
> 
> 
> This isn't acceptable in the gameplay.tsx do this in the index.css file instead

Okay
Let me work on these corrections as fast as possible

**Comment by supreme2580** [comment]
Okay great

**Comment by Dprof-in-tech** [comment]
hey @supreme2580 
I've made the corrections based on the comments above

Also according to a video of the volume screen prototype shared in the telegram group some time back, the chevron arrow has a state of up when open and down when the screen is closed. I have removed this for now, but it is only down right now.

**Comment by supreme2580** [comment]
Hi @Dprof-in-tech I just reviewed your PR again, just one more observation


https://github.com/realm-of-ra/mancala/assets/100731397/d96df50f-7bfb-459f-a32a-3054862508bc

When I touch anything on the popup it automatically close after, the issue might be this

```
{/* End of game board */}
          <div className="flex flex-row items-center justify-between w-full mt-10">
            <div
              className="relative flex flex-row gap-2 items-center justify-center border border-gray-800 rounded-full py-2 px-4 cursor-pointer"
              onClick={toggleDropdown}
            >
```

being the parent of the popup this

```
{isDropdownOpen && (
                <div className="absolute bottom-20 left-[7%] bg-transparent backdrop-blur-md rounded-md shadow-lg px-6 py-4 z-50 w-[240px]">
                  <div className="flex items-center gap-1 justify-center">
                    <img
                      src={playprevious}
                      width={30}
                      height={30}
                      alt="toggle play previous"
                      className="rounded-full cursor-pointer"
                    />
```

So because the popup is a child of the toggle controller when you click on anything on the popup you are triggering the toggle popup controller

**Comment by Dprof-in-tech** [comment]
Yes that was why according to the prototype I had made only the arrow
clickable because I was using a toggle function

**Comment by Dprof-in-tech** [comment]
I could put back the title function to the chevron arrow

**Comment by Dprof-in-tech** [comment]
@supreme2580 

i updated it so that only the chevron arrow toggles the volume bar display

**Comment by supreme2580** [comment]
Checking it out

**Comment by supreme2580** [comment]
Hi @Dprof-in-tech The issue of touching anything on the popup closes the popup still persists, also it'll be cool if the popup and storms in africa width are the same

**Comment by Dprof-in-tech** [comment]
Ok, I'll check it out.

**Comment by supreme2580** [comment]
The issue of it closing everytime anywhere else is clicked is now fixed, but clicking the entire Playing - Storms in africa does not open the popup only the chevron arrow does

**Comment by Dprof-in-tech** [comment]
Unless I modify the toggle function to match this

Do you think I should do that instead of the toggle button that is a one
way click of open and close

**Review by supreme2580 — APPROVED** [review]

**Pull request merged**
